### ISSUE TITLE
dataset path

### ISSUE THREAD

**Issue by xixihawokao** [SuperSupermoon/MedViLL#11]
nice work! 
I followed the "readme" and tried to run this code on VQA-RAD, but i meet some problems about the datasets' path. I revise the "image_root" and "scr_file", and get some path errors like "/home/mimic-cxr/dataset/.....". 
I also tried to change the "fixed_path", but the datasets you provided are not same as the code, like "/home/mimic-cxr/dataset/vqa_image/" .  How can I do?

**Comment by xaleza** [comment]
Have you found a solution for this?

**Comment by SuperSupermoon** [comment]
We fixed some part of data loader.
Please check again!
