### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by jainnipun11** [SuperSupermoon/MedViLL#7]
Hey! I unzipped the images in the suggested path, but still I keep getting the:

FileNotFoundError: [Errno 2] No such file or directory: '/home/data_storage/mimic-cxr/dataset/image_preprocessing/re_512_3ch/Train/s50328096.jpg'

Can you elaborate why this error is coming?

Thanks.

**Comment by ttumyche** [comment]
Hi, jainnipun

I guess that error occurred in [this line](https://github.com/SuperSupermoon/MedViLL/blob/9c258c7890c058f612d9cb0f1e351540a103d817/data/dataset_origin.py#L60) 
How did you define the suggested path? or you can just change 'fixed_path' to yours.

**Comment by jainnipun11** [comment]
Thanks! Resolved the "fixed_path" issue, but now it's giving CUDA out of memory error:

CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 15.78 GiB total capacity; 13.97 GiB already allocated; 240.75 MiB free; 14.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

What to do? Should I decrease the batch size?

**Comment by ttumyche** [comment]
Yup, reduce the batch size to fit your GPU VRAM first.
If that does not solve the error, let me know again

**Comment by jainnipun11** [comment]
Yes! Training started after I reduced the "batch_size" from 36 to 15. Thanks.
