### ISSUE TITLE
.jsonl image_path issue

### ISSUE THREAD

**Issue by jainnipun11** [SuperSupermoon/MedViLL#8]
Inside the .jsonl file, the image path mentioned doesn't match with the image path I have for the images. Due to which, **post-training** an error comes:

FileNotFoundError: [Errno 2] No such file or directory: '/home/mimic-cxr/dataset/image_preprocessing/re_512_3ch/Train/s58694447.jpg'

Could you please guide me? Thanks.

**Comment by ttumyche** [comment]
I think it's the same question you asked before, but didn't you solve it that way? or is there another error?
You can just change the image path in the json file to yours.
Can you tell me which line the error occurred?

**Comment by jainnipun11** [comment]
Hey, yes I encountered this issue elsewhere, resolved it. But another error occured:

"'MultimodalBertClf' object has no attribute 'module'"

Can you please guide me through this?

**Comment by rozataheri46** [comment]
> I think it's the same question you asked before, but didn't you solve it that way? or is there another error? You can just change the image path in the json file to yours. Can you tell me which line the error occurred?

hi i need to help for run the code... 
How can I contact you?
