### ISSUE TITLE
Recall calculation

### ISSUE THREAD

**Issue by gefend** [SuperSupermoon/MedViLL#9]
In the results provided in the paper did you considered a positive pair for the recall calculation only as the original report- image pair or as all pairs with same positive chexpert labels?
In addition, you mentioned in the paper that during inference, in each trial a model is given 100 report-image pairs , is the retrieval is in each time out of 100 and the average provided in the paper is the average of all those 15 100 pairs?

**Comment by ttumyche** [comment]
Hi, gefend

First, we considered all pairs with the same positive labels for the recall calculation.
Second, the model received 100 pairs in one trial, and we averaged the scores.
By the way, I am not sure what 15 you mean.
